// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class TestNavigateTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Close();
  }
  [Test]
  public void testNavigate() {
    driver.Navigate().GoToUrl("https://www.amazon.com.br/");
    driver.Manage().Window.Size = new System.Drawing.Size(1936, 1056);
    driver.FindElement(By.LinkText("Mais Vendidos")).Click();
    driver.FindElement(By.CssSelector(".\\_p13n-zg-banner-landing-page-header_style_zgLandingPageBannerTitleContainer__3pQqv")).Click();
    driver.FindElement(By.CssSelector(".\\_p13n-zg-banner-landing-page-header_style_zgLandingPageBannerTitleContainer__3pQqv")).Click();
    Assert.That(driver.FindElement(By.Id("zg_banner_text")).Text, Is.EqualTo("Mais vendidos"));
    driver.FindElement(By.LinkText("Livros")).Click();
    driver.FindElement(By.CssSelector(".a-text-center > h2")).Click();
    Assert.That(driver.FindElement(By.CssSelector(".a-text-center > h2")).Text, Is.EqualTo("Loja de Livros"));
    driver.FindElement(By.LinkText("Casa")).Click();
    Assert.That(driver.FindElement(By.CssSelector("h1 > b")).Text, Is.EqualTo("Tudo em Casa e Decoração"));
    driver.FindElement(By.LinkText("Eletrônicos")).Click();
    Assert.That(driver.FindElement(By.CssSelector(".bxc-grid__text > h1")).Text, Is.EqualTo("Eletrônicos e Tecnologia"));
    driver.FindElement(By.LinkText("Games")).Click();
  }
}
