// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class TestAddCepInvalidoTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Close();
  }
  [Test]
  public void testAddCepInvalido() {
    driver.Navigate().GoToUrl("https://www.amazon.com.br/");
    driver.Manage().Window.Size = new System.Drawing.Size(1936, 1056);
    {
      var element = driver.FindElement(By.LinkText("Venda na Amazon"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element).Perform();
    }
    driver.FindElement(By.Id("glow-ingress-line1")).Click();
    driver.FindElement(By.Id("GLUXZipUpdateInput_0")).Click();
    driver.FindElement(By.Id("GLUXZipUpdateInput_0")).SendKeys("49620");
    driver.FindElement(By.Id("GLUXZipUpdateInput_1")).SendKeys("010");
    driver.FindElement(By.CssSelector("#GLUXZipUpdate .a-button-input")).Click();
    driver.FindElement(By.Id("GLUXZipInputSection")).Click();
    Assert.That(driver.FindElement(By.CssSelector("#GLUXZipError .a-box-inner > div")).Text, Is.EqualTo("Insira um CEP válido"));
  }
}
